import * as funcoes from './funcoes'


module.exports = {
  'pesquisa agencias'(browser) {
    browser
      .url('http://novogic.des.caixa')
      .click('.xn-openable')
      .pause(5000)
      .click('.xn-openable > ul > li > a')
      .waitForElementVisible('#no_agencia', 10000)
      .setValue('#no_agencia', 'AP')
      .click('input[type=radio][value=""]')
      .click('.btn:nth-of-type(2)')
      .pause(10000)
      .assert.elementNotPresent('#sf-resetcontent')
      .click('a[title="Auditoria Tabela"]')
      .assert.elementNotPresent('#sf-resetcontent')
      .click('a[title=Importar]')
      .assert.elementNotPresent('#sf-resetcontent')
      .pause(5000)
    browser.end()
  },
  'pesquisa ambientes de atendimento'(browser) {
    browser
      .url('http://novogic.des.caixa')
      .click('.xn-openable')
      .pause(5000)
      .click('.xn-openable > ul > li:nth-of-type(2) > a')
      .waitForElementVisible('input[name=no_ambiente]', 5000)
      .setValue('input[name=no_ambiente]', 'CN')
      .waitForElementVisible('input[name=sg_ambiente]', 5000)
      .setValue('input[name=sg_ambiente]', 'CERAT')
      .waitForElementVisible('input[name=nu_cgc]', 5000)
      .setValue('input[name=nu_cgc]', '7392')
      .click('input[type=radio][value=""]')
      .click('.btn:nth-of-type(2)')
      .pause(10000)
    funcoes.acoes(browser)
    funcoes.sweetalert(browser)
    browser.end()
  },
  'pesquisa Aplicativos'(browser) {
    browser
      .url('http://novogic.des.caixa')
      .click('.xn-openable')
      .pause(5000)
      .click('.xn-openable > ul > li:nth-of-type(3) > a')
      .waitForElementVisible('input[name=no_aplicativo]', 5000)
      .setValue('input[name=no_aplicativo]', 'SIACC')
      .click('input[type=radio][value=""]')
      .click('.btn:nth-of-type(2)')
      .pause(10000)
    funcoes.acoes(browser)
    funcoes.sweetalert(browser)
    browser.end()
  },
  'pesquisa Caixa Postal'(browser) {
    browser
      .url('http://novogic.des.caixa')
      .click('.xn-openable')
      .pause(5000)
      .click('.xn-openable > ul > li:nth-of-type(4) > a')
      .waitForElementVisible('input[name=no_caixa_postal]', 5000)
      .setValue('input[name=no_caixa_postal]', 'ceatesa')
      .click('input[type=radio][value=""]')
      .click('.btn:nth-of-type(2)')
      .pause(10000)
    funcoes.acoes(browser)
    funcoes.sweetalert(browser)
    browser.end()
  },
  'pesquisa Clientes'(browser) {
    browser
      .url('http://novogic.des.caixa')
      .click('.xn-openable')
      .pause(5000)
      .click('.xn-openable > ul > li:nth-of-type(5) > a')
      .waitForElementVisible('input[name=no_cliente]', 10000)
      .setValue('input[name=no_cliente]', 'MARIA')
      .click('input[type=radio][value=""]')
      .click('.btn:nth-of-type(2)')
      .pause(10000)
    funcoes.acoes(browser)
    funcoes.sweetalert(browser)
    browser.end()
  },
  'pesquisa Equipes'(browser) {
    browser
      .url('http://novogic.des.caixa')
      .click('.xn-openable')
      .pause(5000)
      .click('.xn-openable > ul > li:nth-of-type(6) > a')
      .waitForElementVisible('input[name=no_equipe]', 10000)
      .setValue('input[name=no_equipe]', 'equipe')
      .click('#co_ambiente_atendimento_chosen')
      .click('.chosen-drop > .chosen-results > li:nth-of-type(5)')
      .click('input[type=radio][value=""]')
      .click('.btn:nth-of-type(2)')
      .pause(10000)
    funcoes.acoes(browser)
    funcoes.sweetalert(browser)
    browser.end()
  },
  'pesquisa Filas'(browser) {
    browser
      .url('http://novogic.des.caixa')
      .click('.xn-openable')
      .pause(5000)
      .click('.xn-openable > ul > li:nth-of-type(7) > a')
      .waitForElementVisible('input[name=no_fila]', 10000)
      .setValue('input[name=no_fila]', 'CXA')
      .click('#co_segmento_chosen')
      .click('.chosen-drop > .chosen-results > li:nth-of-type(3)')
      .pause(5000)
      .click('#co_ambiente_chosen')
      .click('.chosen-drop > .chosen-results > li:nth-of-type(5)')
      .click('input[type=radio][value=""]')
      .click('.btn:nth-of-type(2)')
      .pause(10000)
    funcoes.acoes(browser)
    funcoes.sweetalert(browser)
    browser.end()
  },
  'pesquisa gerencia'(browser) {
    browser
      .url('http://novogic.des.caixa')
      .click('.xn-openable')
      .pause(5000)
      .click('.xn-openable > ul > li:nth-of-type(8) > a')
      .waitForElementVisible('input[name=no_gerencia]', 10000)
      .setValue('input[name=no_gerencia]', 'GESTAO')
      .click('input[type=radio][value=""]')
      .click('.btn:nth-of-type(2)')
      .pause(10000)
    funcoes.acoes(browser)
    funcoes.sweetalert(browser)
    browser.end()
  },
  'pesquisa Incidentes'(browser) {
    browser
      .url('http://novogic.des.caixa')
      .click('.xn-openable')
      .pause(5000)
      .click('.xn-openable > ul > li:nth-of-type(9) > a')
      .waitForElementVisible('input[name=no_incidente]', 10000)
      .setValue('input[name=no_incidente]', '001')
      .click('#co_fila_chosen')
      .click('.chosen-drop > .chosen-results > li:nth-of-type(29)')
      .click('input[type=radio][value=""]')
      .click('.btn:nth-of-type(2)')
      .pause(10000)
    funcoes.acoes(browser)
    funcoes.sweetalert(browser)
    browser.end()
  },
  'pesquisa itens de respostas'(browser) {
    browser
      .url('http://novogic.des.caixa')
      .click('.xn-openable')
      .pause(5000)
      .click('.xn-openable > ul > li:nth-of-type(10) > a')
      .waitForElementPresent('input[id=no_item_resposta]', 10000)
      .setValue('input[id=no_item_resposta]', 'TESTE')
      .click('input[type=radio][value=""]')
      .click('.btn:nth-of-type(2)')
      .pause(10000)
    funcoes.acoes(browser)
    funcoes.sweetalert(browser)
    browser.end()
  },
  'pesquisa Links uteis'(browser) {
    browser
      .url('http://novogic.des.caixa')
      .click('.xn-openable')
      .pause(5000)
      .click('.xn-openable > ul > li:nth-of-type(11) > a')
      .waitForElementVisible('input[name=no_link_util]', 10000)
      .setValue('input[name=no_link_util]', 'VAN')
      .waitForElementVisible('input[name=de_link_util]', 10000)
      .setValue('input[name=de_link_util]', 'CAIXA')
      .click('input[type=radio][value=""]')
      .click('.btn:nth-of-type(2)')
      .pause(10000)
    funcoes.acoes(browser)
    funcoes.sweetalert(browser)
    browser.end()
  },
  'pesquisa Meios Acionamentos'(browser) {
    browser
      .url('http://novogic.des.caixa')
      .click('.xn-openable')
      .pause(5000)
      .click('.xn-openable > ul > li:nth-of-type(12) > a')
      .waitForElementVisible('input[name=no_meio_acionamento]', 10000)
      .setValue('input[name=no_meio_acionamento]', 'GIC')
      .click('input[type=checkbox][value="S"]')
      .click('input[type=radio][value=""]')
      .click('.btn:nth-of-type(2)')
      .pause(10000)
    funcoes.acoes(browser)
    funcoes.sweetalert(browser)
    browser.end()
  },
  'pesquisa Mensagens Padrões'(browser) {
    browser
      .url('http://novogic.des.caixa')
      .click('.xn-openable')
      .pause(5000)
      .click('.xn-openable > ul > li:nth-of-type(13) > a')
      .waitForElementVisible('input[name=no_mensagem_email_padrao]', 10000)
      .setValue('input[name=no_mensagem_email_padrao]', 'TESTE')
      .click('input[type=radio][value=""]')
      .click('.btn:nth-of-type(2)')
      .pause(10000)
    funcoes.acoes(browser)
    funcoes.sweetalert(browser)
    browser.end()
  },
  'pesquisa Motivos de não resolução'(browser) {
    browser
      .url('http://novogic.des.caixa')
      .click('.xn-openable')
      .pause(5000)
      .click('.xn-openable > ul > li:nth-of-type(14) > a')
      .waitForElementVisible('input[name=de_motivo_interrupcao]', 10000)
      .setValue('input[name=de_motivo_interrupcao]', 'IMPROCEDENTE')
      .click('input[type=radio][value=""]')
      .click('.btn:nth-of-type(2)')
      .pause(10000)
    funcoes.acoes(browser)
    funcoes.sweetalert(browser)
    browser.end()
  },
  'pesquisa Motivos febraban'(browser) {
    browser
      .url('http://novogic.des.caixa')
      .click('.xn-openable')
      .pause(5000)
      .click('.xn-openable > ul > li:nth-of-type(15) > a')
      .waitForElementVisible('input[name=co_externo_motivo_febraban]', 15000)
      .setValue('input[name=co_externo_motivo_febraban]', '200')
      .setValue('input[name=no_motivo_febraban]', 'co')
      .click('#co_categoria_febraban_chosen')
      .pause(5000)
      .click('.chosen-drop > .chosen-results > li:nth-of-type(4)')
      .click('input[type=radio][value=""]')
      .click('.btn:nth-of-type(2)')
      .pause(10000)
    funcoes.acoes(browser)
    funcoes.sweetalert(browser)
    browser.end()
  },
  'pesquisa Motivos SIOUV'(browser) {
    browser
      .url('http://novogic.des.caixa')
      .click('.xn-openable')
      .pause(5000)
      .click('.xn-openable > ul > li:nth-of-type(16) > a')
      .waitForElementVisible('input[name=de_motivo_siouv]', 15000)
      .setValue('input[name=de_motivo_siouv]', 'Pagamento')
      .click('input[type=radio][value=""]')
      .click('.btn:nth-of-type(2)')
      .pause(10000)
    funcoes.acoes(browser)
    funcoes.sweetalert(browser)
    browser.end()
  },
  'pesquisa Natureza'(browser) {
    browser
      .url('http://novogic.des.caixa')
      .click('.xn-openable')
      .pause(5000)
      .click('.xn-openable > ul > li:nth-of-type(17) > a')
      .waitForElementVisible('input[name=no_natureza]', 15000)
      .setValue('input[name=no_natureza]', 'elogio')
      .click('input[type=radio][value=""]')
      .click('.btn:nth-of-type(2)')
      .pause(10000)
    funcoes.acoes(browser)
    funcoes.sweetalert(browser)
    browser.end()
  },
  'pesquisa Paginas de suporte'(browser) {
    browser
      .url('http://novogic.des.caixa')
      .click('.xn-openable')
      .pause(5000)
      .click('.xn-openable > ul > li:nth-of-type(18) > a')
      .waitForElementVisible('input[name=no_menu_suporte]', 15000)
      .setValue('input[name=no_menu_suporte]', 'MANUAL')
      .click('#co_fila_chosen')
      .click('.chosen-drop > .chosen-results > li:nth-of-type(62)')
      .pause(5000)
      .click('#co_produto_chosen')
      .pause(5000)
      .click('.chosen-drop > .chosen-results > li')
      .click('input[type=radio][value=""]')
      .click('.btn:nth-of-type(2)')
      .pause(10000)
    funcoes.acoes(browser)
    funcoes.sweetalert(browser)
      .pause(5000)
      .click('a[title="Clonar"]')
      .assert.elementNotPresent('#sf-resetcontent')
    browser.back()
      .pause(5000)
    browser.end()
  },
  'pesquisas Pastas'(browser) {
    browser
      .url('http://novogic.des.caixa')
      .click('.xn-openable')
      .pause(5000)
      .click('.xn-openable > ul > li:nth-of-type(19) > a')
      .waitForElementVisible('input[name=no_pasta]', 10000)
      .setValue('input[name=no_pasta]', '2º')
      .click('#nu_nivel_atendimento_chosen')
      .click('.chosen-drop > .chosen-results > li:nth-of-type(2)')
      .click('#co_ambiente_chosen')
      .click('.chosen-drop > .chosen-results > li:nth-of-type(5)')
      .click('#co_fila_chosen')
      .click('.chosen-drop > .chosen-results > li:nth-of-type(5)')
      .click('input[type=checkbox][name=ic_telefonico][value="S"]')
      .click('input[type=radio][value=""]')
      .click('.btn:nth-of-type(2)')
      .pause(10000)
    funcoes.acoes(browser)
    funcoes.sweetalert(browser)
    browser.end()
  },
  'pesquisas prefeituras'(browser) {
    browser
      .url('http://novogic.des.caixa')
      .click('.xn-openable')
      .pause(5000)
      .click('.xn-openable > ul > li:nth-of-type(20) > a')
      .waitForElementVisible('input[name=nu_cnpj]', 10000)
      .setValue('input[name=nu_cnpj]', '')
      .click('#co_uf_chosen')
      .click('.chosen-drop > .chosen-results > li:nth-of-type(5)')
      .setValue('input[name=no_municipio]', 'Barra')
      .setValue('input[name=no_agencia]', 'Barra')
      .click('#co_gifab_chosen')
      .click('.chosen-drop > .chosen-results > li:nth-of-type(37)')
      .click('#co_sr_chosen')
      .click('.chosen-drop > .chosen-results > li:nth-of-type(117)')
      .click('.btn:nth-of-type(2)')
      .pause(10000)
      .click('a[title="Auditoria Tabela"]')
      .assert.elementNotPresent('#sf-resetcontent')
      .pause(5000)
      .click('a[title="Importar dados"]')
      .assert.elementNotPresent('#sf-resetcontent')
    browser.end()
  },
  'pesquisas produtos'(browser) {
    browser
      .url('http://novogic.des.caixa')
      .click('.xn-openable')
      .pause(5000)
      .click('.xn-openable > ul > li:nth-of-type(21) > a')
      .waitForElementVisible('input[name=no_produto]', 10000)
      .setValue('input[name=no_produto]', 'despesas')
      .click('#co_fila_chosen')
      .click('.chosen-drop > .chosen-results > li:nth-of-type(5)')
      .click('input[type=radio][value=""]')
      .click('.btn:nth-of-type(2)')
      .pause(10000)
      .click('a[title="Página de Suporte"]')
      .pause(5000)
    funcoes.acoes(browser)
    funcoes.sweetalert(browser)
    browser.end()
  },
  'pesquisas questionarios'(browser) { 
    browser
      .url('http://novogic.des.caixa')
      .click('.xn-openable')
      .pause(5000)
      .click('.xn-openable > ul > li:nth-of-type(22) > a')
      .waitForElementVisible('input[name=no_pergunta]', 10000)
      .setValue('input[name=no_pergunta]', 'teste')
      .click('input[type=radio][value="T"]')
      .click('.btn:nth-of-type(2)')
      .pause(10000)
    funcoes.acoes(browser)
    funcoes.sweetalert(browser)
    browser.end()
  },
  // 'pesquisas questionario SIGSC'(browser) { //php error
  //   browser
  //   .url('http://novogic.des.caixa')
  // .click('.xn-openable')
  // .pause(5000)
  // .click('.xn-openable > ul > li:nth-of-type(23) > a')
  //   .waitForElementVisible('input[name=no_remetente]', 10000)
  //   .setValue('input[name=no_remetente]', 'teste')
  //   .setValue('input[name=no_email]', 'teste')
  //   .click('#co_equipe_chosen')
  //   .click('.chosen-drop > .chosen-results > li:nth-of-type(4)')
  //   .click('input[type=radio][value=""]')
  //   .click('.btn:nth-of-type(2)')
  //   .pause(10000)
  //   .click('a[title="Auditoria Tabela"]')
  //   .assert.elementNotPresent('#sf-resetcontent')
  //   .click('a[title=Novo]')
  //   .pause(5000)
  //   browser.back()
  //   .pause(5000)
  //   .click('a[title="Auditoria Registro"]')
  //   .assert.elementNotPresent('#sf-resetcontent')
  //   .pause(5000)
  //   .click('a[title="Visualizar"]')
  //   .assert.elementNotPresent('#sf-resetcontent')
  //   browser.back()
  //   .pause(5000)
  //   .click('a[title="Editar"]')
  //   .assert.elementNotPresent('#sf-resetcontent')
  //   browser.back()
  //   .pause(5000)
  //   browser.end()
  // },
  // 'pesquisas remetentes'(browser) { // não ha dados para teste
  //   browser
  //     .url('http://novogic.des.caixa')
  //     .click('.xn-openable')
  //     .pause(5000)
  //     .click('.xn-openable > ul > li:nth-of-type(24) > a')
  //     .waitForElementVisible('input[name=no_remetente]', 10000)
  //     .setValue('input[name=no_remetente]', 'teste')
  //     .setValue('input[name=no_email]', 'teste')
  //     .click('#co_equipe_chosen')
  //     .click('.chosen-drop > .chosen-results > li:nth-of-type(4)')
  //     .click('input[type=radio][value=""]')
  //     .click('.btn:nth-of-type(2)')
  //     .pause(10000)
  //   funcoes.acoes(browser)
  //   funcoes.sweetalert(browser)
  //   browser.end()
  // },
  'pesquisas segmentos'(browser) {
    browser
      .url('http://novogic.des.caixa')
      .click('.xn-openable')
      .pause(5000)
      .click('.xn-openable > ul > li:nth-of-type(25) > a')
      .waitForElementVisible('input[name=no_segmento]', 10000)
      .setValue('input[name=no_segmento]', 'canais')
      .click('input[type=radio][value=""]')
      .click('.btn:nth-of-type(2)')
      .pause(10000)
    funcoes.acoes(browser)
    funcoes.sweetalert(browser)
    browser.end()
  },
  // 'pesquisas status chamado'(browser) { //botao de editar sem nome 
  //   browser
  //     .url('http://novogic.des.caixa')
  //     .click('.xn-openable')
  //     .pause(5000)
  //     .click('.xn-openable > ul > li:nth-of-type(26) > a')
  //     .waitForElementVisible('input[name=no_status_chamado]', 10000)
  //     .setValue('input[name=no_status_chamado]', 'acompanhamento')
  //     .click('#ic_status_fechado_chosen')
  //     .click('.chosen-drop > .chosen-results > li:nth-of-type(2)')
  //     .click('input[type=radio][value=""]')
  //     .click('.btn:nth-of-type(2)')
  //     .pause(10000)
  //   funcoes.acoes(browser)
  //   funcoes.sweetalert(browser)
  //   browser.end()
  // },
  'pesquisas superintendencias'(browser) {
    browser
      .url('http://novogic.des.caixa')
      .click('.xn-openable')
      .pause(5000)
      .click('.xn-openable > ul > li:nth-of-type(27) > a')
      .waitForElementVisible('input[name=no_superintendencia]', 10000)
      .setValue('input[name=no_superintendencia]', 'su')
      .setValue('input[name=sg_superintendencia]', 'su')
      .click('input[type=radio][value=""]')
      .click('.btn:nth-of-type(2)')
      .pause(10000)
    funcoes.acoes(browser)
    funcoes.sweetalert(browser)
    browser.end()
  },
  'pesquisas tipos convenios'(browser) {
    browser
      .url('http://novogic.des.caixa')
      .click('.xn-openable')
      .pause(5000)
      .click('.xn-openable > ul > li:nth-of-type(28) > a')
      .waitForElementVisible('input[name=no_convenio]', 10000)
      .setValue('input[name=no_convenio]', 'sicap')
      .click('input[type=radio][value=""]')
      .click('.btn:nth-of-type(2)')
      .pause(10000)
    funcoes.acoes(browser)
    funcoes.sweetalert(browser)
    browser.end()
  },
  'pesquisa tipos de soluções'(browser) {
    browser
      .url('http://novogic.des.caixa')
      .click('.xn-openable')
      .pause(5000)
      .click('.xn-openable > ul > li:nth-of-type(29) > a')
      .waitForElementVisible('input[name=no_tipo_solucao]', 10000)
      .setValue('input[name=no_tipo_solucao]', 'classificar')
      .click('#co_fila_chosen')
      .click('.chosen-drop > .chosen-results > li:nth-of-type(30)')
      .click('#co_produto_chosen')
      .click('.chosen-drop > .chosen-results > li:nth-of-type(2)')
      .click('input[type=radio][value=""]')
      .click('.btn:nth-of-type(2)')
      .pause(10000)
    funcoes.acoes(browser)
    funcoes.sweetalert(browser)
    browser.end()
  },
  'pesquisa VANS'(browser) {
    browser
      .url('http://novogic.des.caixa')
      .click('.xn-openable')
      .pause(5000)
      .click('.xn-openable > ul > li:nth-of-type(30) > a')
      .waitForElementVisible('input[name=no_van]', 15000)
      .setValue('input[name=no_van]', 'GXS')
      .click('input[type=radio][value=""]')
      .click('.btn:nth-of-type(2)')
      .pause(10000)
    funcoes.acoes(browser)
    funcoes.sweetalert(browser)
    browser.end()
  },
}