module.exports = {
'pesquisa Segurança funcionalidades'(browser) {
      browser
      .url('http://novogic.des.caixa')
  .click('.xn-openable:nth-of-type(5)')
  .pause(10000)
  .click('.xn-openable:nth-of-type(5) > ul > li:nth-of-type(2) > a')
  .click('input[name=no_funcionalidade]')
  .setValue('input[name=no_funcionalidade]', 'chamados')
  .waitForElementVisible('div[id=co_modulo_chosen]', 5000)
  .click('#co_modulo_chosen')
  .pause(5000)
  .click('.chosen-drop > .chosen-results > li:nth-of-type(2)')
  .click('input[type=radio][value="T"]')
  .click('.btn:nth-of-type(2)')
  .assert.elementNotPresent('sf-resetcontent')
      .pause(10000)
      .click('a[title="Auditoria Tabela"]')
    .assert.elementNotPresent('#sf-resetcontent')
    .click('a[title=Novo]')
    .assert.elementNotPresent('#sf-resetcontent')
    .pause(5000)
    browser.back()
    .pause(5000)
    .click('a[title="Auditoria Registro"]')
    .assert.elementNotPresent('#sf-resetcontent')
    .pause(5000)
    .click('a[title="Visualizar"]')
    .assert.elementNotPresent('#sf-resetcontent')
    browser.back()
    .pause(5000)
    .click('a[title="Editar"]')
    .assert.elementNotPresent('#sf-resetcontent')
    browser.back()
    .pause(5000)
    .click('button[type=submit]')
    .pause(5000)
    .click('button[type=submit]')
    .pause(5000)
      browser.end()
    },
    'pesquisa Segurança parametros'(browser) {
      browser
      .url('http://novogic.des.caixa')
  .click('.xn-openable:nth-of-type(5)')
  .pause(5000)
  .click('.xn-openable:nth-of-type(5) > ul > li:nth-of-type(3) > a')
  .waitForElementVisible('#no_parametro', 5000)
  .setValue('input[name=no_parametro]', 'TMA')
  .waitForElementVisible('#de_valor', 5000)
  .setValue('input[name=de_valor]', '3')
  .click('input[type=radio][value=""]')
  .click('.btn:nth-of-type(2)')
  .pause(5000)
  .click('a[title="Auditoria Tabela"]')
    .assert.elementNotPresent('#sf-resetcontent')
    .click('a[title=Novo]')
    .assert.elementNotPresent('#sf-resetcontent')
    .pause(5000)
    browser.back()
    .pause(5000)
    .click('a[title="Auditoria Registro"]')
    .assert.elementNotPresent('#sf-resetcontent')
    .pause(5000)
    .click('a[title="Visualizar"]')
    .assert.elementNotPresent('#sf-resetcontent')
    browser.back()
    .pause(5000)
    .click('a[title="Editar"]')
    .assert.elementNotPresent('#sf-resetcontent')
    browser.back()
    .pause(5000)
    .click('button[type=submit]')
    .pause(5000)
    .click('button[type=submit]')
    .pause(5000)
  browser.end()
    },
    'pesquisa Segurança perfis'(browser) {
      browser
      .url('http://novogic.des.caixa')
  .click('.xn-openable:nth-of-type(5)')
  .pause(5000)
  .click('.xn-openable:nth-of-type(5) > ul > li:nth-of-type(4) > a')
  .waitForElementVisible('input[name=no_perfil]', 5000)
  .setValue('input[name=no_perfil]', 'CAIXA')
  .click('#nu_nivel_atendimento_chosen')
  .click('.chosen-drop > .chosen-results > li:nth-of-type(2)')
  .click('input[type=checkbox][name=ic_eletronico][value="S"]')
  .click('input[type=radio][value="T"]')
  .click('.btn:nth-of-type(2)')
  .pause(5000)
  .click('a[title="Auditoria Tabela"]')
    .assert.elementNotPresent('#sf-resetcontent')
    .click('a[title=Novo]')
    .assert.elementNotPresent('#sf-resetcontent')
    .pause(5000)
    browser.back()
    .click('a[title="Auditoria Registro"]')
    .assert.elementNotPresent('#sf-resetcontent')
    .pause(10000)
    .click('a[title="Visualizar"]')
    .assert.elementNotPresent('#sf-resetcontent')
    browser.back()
    .pause(10000)
    .click('a[title="Editar"]') //adicionar titulo ao icone "editar"
    .assert.elementNotPresent('#sf-resetcontent')
    browser.back()
    .pause(5000)
  browser.end()
    },
    'pesquisa Segurança SQL'(browser) {
      browser
      .url('http://novogic.des.caixa')
  .click('.xn-openable:nth-of-type(5)')
  .pause(5000)
  .click('.xn-openable:nth-of-type(5) > ul > li:nth-of-type(5) > a')
  .pause(5000)
  browser.end()
    },
    'pesquisa Segurança Usuarios'(browser) {
      browser
      .url('http://novogic.des.caixa')
  .click('.xn-openable:nth-of-type(5)')
  .pause(5000)
  .click('.xn-openable:nth-of-type(5) > ul > li:nth-of-type(6) > a')
  .setValue('input[name="name"]', 'AD')
  .click('#co_perfil_chosen')
  .click('.chosen-drop > .chosen-results > li:nth-of-type(7)')
  .click('input[type=radio][value="T"]')
  .click('.btn:nth-of-type(2)')
  .assert.elementNotPresent('#sf-resetcontent')
  .pause(5000)
  .click('a[title="Auditoria Tabela"]')
    .assert.elementNotPresent('#sf-resetcontent')
    .click('a[title=Novo]')
    .pause(5000)
    browser.back()
    .pause(5000)
    .click('a[title="Auditoria Registro"]')
    .assert.elementNotPresent('#sf-resetcontent')
    .pause(5000)
    .click('a[title="Visualizar"]')
    .assert.elementNotPresent('#sf-resetcontent')
    browser.back()
    .pause(5000)
    .click('a[title="Editar"]') //adicionar o titulo "Editar"
    .assert.elementNotPresent('#sf-resetcontent')
    browser.back()
    .pause(5000)
    .click('button[type=submit]')
    .pause(5000)
    .click('button[type=submit]')
    .pause(5000)
  browser.end()
    },
    'pesquisa Segurança auditoria'(browser) {
      browser
      .url('http://novogic.des.caixa')
  .click('.xn-openable:nth-of-type(5)')
  .pause(5000)
  .click('.xn-openable:nth-of-type(5) > ul > li > a')
  .waitForElementPresent('div[id=co_funcionalidade_chosen]', 5000)
.click('#co_funcionalidade_chosen')
.pause(5000)
.click('.chosen-drop > .chosen-results > li:nth-of-type(3)')
.pause(5000)
.useXpath()
.click('//*[@id="search"]/div[1]/div[2]/div')
.useCss()
  .click('.btn:nth-of-type(2)')
.pause(5000)
browser.end()
    },
}